service: lashic-dx
 
provider:
 name: aws
 stage: dev
 profile: hadi_aws_user
 runtime: python3.8.10
 region: us-east-1
 memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  - ${file(./cf_template.yml)}	

custom:
  pythonRequirements:
    fileName: requirements.txt
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false

functions:
  app:
    handler: wsgi.handler
    events:
     - http: ANY /
    #  - http: 'ANY {proxy+}'