name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy to aws
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://test.com
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: pip3 install -r requirements.txt
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage production
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}